### ISSUE TITLE
Use english as source language

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#1]
Please use english as source language for dialogs (e.g. https://github.com/linuxmuster/linuxmuster-base7/blob/master/lib/setup.d/b_dialog.py). This will make it much easier to translate it to other languages later.

**Comment by zefanja** [comment]
During setup some questions are in German, some are in English.

**Comment by HappyBasher** [comment]
I don't see any more german dialogs.
