### ISSUE TITLE
smb.conf faulty

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-base7#100]
Like in ask mentioned: https://ask.linuxmuster.net/t/ist-server-ein-problem/4099/34

the smb.conf got corrupted in one update.
the right options should look like this:

```
rpc_server:spoolss = external
rpc_daemon:spoolssd = fork
spoolss:architecture = Windows x64
printing = cups
printcap name = cups
```

**Comment by jolly-jump** [comment]
smb.conf got corrupted, now mentioned here: https://ask.linuxmuster.net/t/fehlerhafte-eintraege-in-smb-conf/5628 since it was moved.

**Comment by HappyBasher** [comment]
At least the reason was that python's configparser does not deal with colons in keywords.
