### ISSUE TITLE
How to add additional [global] options in smb.conf without getting overridden during an update?

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#108]
Our freeradius server is running on our lmnv7 server. I have to include `ntlm auth = mschapv2-and-ntlmv2-only` in the `[global]` section of `smb.conf` for authentification. During the last update all custom options were removed and our users couldn't login to the wifi anymore.

What is the proper way to include custom options in the `[global]` section? I know of `smb.conf.admin`, but it does not work for sections, that are already defined in `smb.conf`, so I can't include it there.

**Comment by HappyBasher** [comment]
@zefanja  

> so I can't include it there

Sure you can. `smb.conf.admin` is included at the end so options defined here overwrite options defined before.

**Comment by zefanja** [comment]
This is what I thought, too, but it looks like, that it does not work (at least for `ntlm auth = mschapv2-and-ntlmv2-only`), see also https://ask.linuxmuster.net/t/wpa2-enterprise-mit-freeradius-auf-server-docker/5910/3
