### ISSUE TITLE
Update schoolname in setup.ini

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-base7#109]
Hello,

This question concern both base7 and sophomorix4 (@jeffbeck).
If I really understand the concept, it's probably not intended to modify the content of `/var/lib/linuxmuster/setup.ini`, and I see that the value of schoolname exists in both `setup.ini` and `school.conf`.

How is it planned to update this value ? Only in `school.conf` (then the value in `setup.ini` would be inconsistent ), or in `setup.ini` and then run a script to update the value in `school.conf` ?

Thanks

Arnaud

**Comment by HappyBasher** [comment]
Hi Arnaud,

> in setup.ini and then run a script to update the value in school.conf
I would prefer this way, so that the values are consistent.

Regards, Thomas

**Comment by kiarn** [comment]
Ok, thanks, I will do it this way in the webui.
I'm wondering why do need sophomorix to make a double of this option : it would be easier to let it stored in `setup.ini` and to get the value from `setup.ini` if needed.

**Comment by HappyBasher** [comment]
Is this actually done now?

**Comment by kiarn** [comment]
No, I fully forgot this one in the holidays.

**Comment by kiarn** [comment]
Done with https://github.com/linuxmuster/linuxmuster-webui7/commit/89f0dc1611d78600545f3a89ecd1e301562b6885
