### ISSUE TITLE
Systemzeit der opnsense stimmt nicht

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-base7#11]
Die Systemzeit der Firewall stand auf UTC, ich habe sie umgestellt auf Europe/Berlin, dann ging sie nicht mehr 2 Stunden falsch (nach)

Holger

**Comment by HappyBasher** [comment]
Die OPNsense Sytemzeit ist per Default auf UTC/GMT eingestellt. Das ist nun mal MESZ-2. Die Serverzeit auf UTC eingestellt zu lassen ist durchaus üblich, um international komptatibel zu sein. Die Zeit ist aber nicht "falsch". Der Server hat deshalb genau dieselbe Zeit wie die Clients, die auf Europe/Berlin eingestellt sind. Wer gerne die lokale Zeit auf dem Server hat, kann sie ja einstellen.
