### ISSUE TITLE
Where are the Downloads?

### ISSUE THREAD

**Issue by hackbert** [linuxmuster/linuxmuster-base7#114]
Hello,

thx a lot for your work! I was searching the Downloads.

Once they where here: 
https://github.com/linuxmuster/linuxmuster-base7/wiki/Die-Appliances

They should be here now (according to the old page):
https://docs.linuxmuster.net/de/latest/getting-started/prerequisites.html#download

But the #download does not exist. After a lot of searching I found them here:
https://download.linuxmuster.net/ova/v7/latest/

Maybe one could re-link these Downloads somewhere more visible.

**Comment by HappyBasher** [comment]
Thanks for the hint. The lnks are now updated.
