### ISSUE TITLE
MAX_UPLOADS linbo-bittorrent

### ISSUE THREAD

**Issue by teacherrust** [linuxmuster/linuxmuster-base7#131]
Hallo,

es wäre hilfreich, wenn in
/etc/default/linbo-bittorrent
als defalult

MAX_UPLOADS=40
anstatt
MAX_UPLOADS=4

stehen würde.

VG

**Comment by HappyBasher** [comment]
Reason?

**Comment by HappyBasher** [comment]
BTW, wrong repo.
