### ISSUE TITLE
linuxmuster-opnsense-reset fails

### ISSUE THREAD

**Issue by FreeInMind** [linuxmuster/linuxmuster-base7#136]
OPNSense was installed new.
Then linuxmuster-opnsense-reset run on server doesn't work:

root@server:~# linuxmuster-opnsense-reset 
#### linuxmuster-opnsense-reset 2022-02-07 11:29:26                       ####
Sets the firewall to the state after setup.
Custom adjustments made since then are lost.
Note: The firewall will be restartet during the process.
Do you want to continue (YES)? YES
#### * -> "exit"                                                          ####
/usr/lib/python3/dist-packages/paramiko/rsakey.py:119: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/rsakey.py:99: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/dsskey.py:114: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(hashes.SHA1())
/usr/lib/python3/dist-packages/paramiko/ecdsakey.py:184: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = self.signing_key.signer(ecdsa)
#### * Execution finished successfully.                                   ####
------------------------------------------------------------------------------
#### Downloading firewall configuration:                                  ####
/usr/lib/python3/dist-packages/paramiko/rsakey.py:119: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/rsakey.py:99: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/dsskey.py:114: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(hashes.SHA1())
/usr/lib/python3/dist-packages/paramiko/ecdsakey.py:184: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = self.signing_key.signer(ecdsa)
#### Timeout!                                                             ####
root@server:~# linuxmuster-opnsense-reset 
#### linuxmuster-opnsense-reset 2022-02-07 14:11:53                       ####
Sets the firewall to the state after setup.
Custom adjustments made since then are lost.
Note: The firewall will be restartet during the process.
Do you want to continue (YES)? YES
#### * -> "exit"                                                          ####
/usr/lib/python3/dist-packages/paramiko/rsakey.py:119: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/rsakey.py:99: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/dsskey.py:114: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(hashes.SHA1())
/usr/lib/python3/dist-packages/paramiko/ecdsakey.py:184: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = self.signing_key.signer(ecdsa)
#### * Execution finished successfully.                                   ####
------------------------------------------------------------------------------
#### Downloading firewall configuration:                                  ####
/usr/lib/python3/dist-packages/paramiko/rsakey.py:119: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/rsakey.py:99: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
/usr/lib/python3/dist-packages/paramiko/dsskey.py:114: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(hashes.SHA1())
/usr/lib/python3/dist-packages/paramiko/ecdsakey.py:184: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = self.signing_key.signer(ecdsa)
#### Deleting old keytab.                                                 ####
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 360, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 370, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'firewall.linuxmuster.lan' doesn't match 'firewall.gymneureut.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='firewall.linuxmuster.lan', port=443): Max retries exceeded with url: /api/proxysso/service/deletekeytab (Caused by SSLError(CertificateError("hostname 'firewall.linuxmuster.lan' doesn't match 'firewall.gymneureut.de'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/linuxmuster-opnsense-reset", line 108, in <module>
    res = firewallApi('get', apipath)
  File "/usr/lib/linuxmuster/functions.py", line 548, in firewallApi
    req = requests.get(url, auth=(apikey, apisecret))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='firewall.linuxmuster.lan', port=443): Max retries exceeded with url: /api/proxysso/service/deletekeytab (Caused by SSLError(CertificateError("hostname 'firewall.linuxmuster.lan' doesn't match 'firewall.gymneureut.de'",),))
root@server:~#

**Comment by HappyBasher** [comment]
Seems that key based ssh connection with python library paramiko is broken.

**Comment by kiarn** [comment]
Hello,

I will try to test it on my own test server, but this seems more to be a mismatch between hostname and hostname written in the certificate, not really a problem of `paramiko`. @HappyBasher : thanks for your fix !
