### ISSUE TITLE
Old version of paramiko for 18.04

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-base7#139]
Hello,

The version of `python3-paramiko` defined [here](https://github.com/linuxmuster/linuxmuster-base7/blob/1b3501620028a099febdd83a6cd0e4a8060d1cbb/debian/control#L12) is too old in 18.04 (2.0.0) and generates the following error while launching `lmn71-prepare` : 

```
#### Downloading firewall configuration: ####
#### get 10.112.1.254 /conf/config.xml /var/cache/linuxmuster/opnsense.xml ####
Unknown exception: '_EllipticCurvePublicKey' object has no attribute 'verifier'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1795, in run
self.kex_engine.parse_next(ptype, m)
File "/usr/lib/python3/dist-packages/paramiko/kex_gex.py", line 88, in parse_next
return self._parse_kexdh_gex_reply(m)
File "/usr/lib/python3/dist-packages/paramiko/kex_gex.py", line 244, in _parse_kexdh_gex_reply
self.transport._verify_key(host_key, sig)
File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1606, in _verify_key
if not key.verify_ssh_sig(self.H, Message(sig)):
File "/usr/lib/python3/dist-packages/paramiko/ecdsakey.py", line 201, in verify_ssh_sig
verifier = self.verifying_key.verifier(
AttributeError: '_EllipticCurvePublicKey' object has no attribute 'verifier'
'_EllipticCurvePublicKey' object has no attribute 'verifier'
```

Using `paramiko>=2.6.0` solves the problem, so I pinned the version in the webui's requirements : https://github.com/linuxmuster/linuxmuster-webui7/commit/6aa6e1019c3eb34a407f7706e37e1ef81d8dc68d

In Ubuntu 22.04, `python3-paramiko` has the version 2.9.3 today, so I don't if it's necessary to correct this in this repo, but it was necessary to mention it.

Cheers

Arnaud

**Comment by HappyBasher** [comment]
Ok, thanx.
