### ISSUE TITLE
linuxmuster-setup changes root password without notice

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#17]
`linuxmuster-setup` sets the administrator password as the new root password. Is this intended? If yes, there should be a hint or something.

Does it also mean that there is no separate administrator account like in v6.2?

**Comment by HappyBasher** [comment]
It is assumed that the instructions in the [wiki](https://github.com/linuxmuster/linuxmuster-base7/wiki) are read before installation.

**Comment by zefanja** [comment]
Thanks, you are right. 

I just see all the "I can't login anymore" topics in the forum :smile:
