### ISSUE TITLE
Add hint for -p parameter in wiki

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#18]
The `-p` option is expected for `linuxmuster-prepare`, but there is no hint in the wiki. 

https://github.com/linuxmuster/linuxmuster-base7/wiki/Ersteinrichtung-der-Appliances#serveropsidocker

**Comment by HappyBasher** [comment]
At this point the -p paremeter is not expected and necessary because the profile is already set in the initial run of linuxmuster-prepare.

**Comment by HappyBasher** [comment]
This is a bug. Fixed in 0.5.6.

**Comment by HappyBasher** [comment]
BTW, this is an issue for linuxmuster-prepare.

**Comment by zefanja** [comment]
Yes, I noticed that, too. I forgot its not part of linuxmuster-base.
