### ISSUE TITLE
no students.csv / teachers.csv

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#19]
Question: There is no `students.csv` or `teachers.csv` in `/etc/linuxmuster/sophomoric/default-school/`. It is not possible to create new users with the webUI because of this (see [webui7 #2](https://github.com/linuxmuster/linuxmuster-webui7/issues/2)).

Is it planned to put the templates files for students and teachers in this directory?

**Comment by HappyBasher** [comment]
This is an issue for webui.

**Comment by zefanja** [comment]
So there are no plans to put templates file in the default-school directory like `devices.csv`?

**Comment by HappyBasher** [comment]
Don't know. Please ask sophomorix dept.
