### ISSUE TITLE
Skip-Firewall not working in unattanded mode

### ISSUE THREAD

**Issue by netzint** [linuxmuster/linuxmuster-base7#20]
Details on: https://github.com/linuxmuster/linuxmuster-webui7/issues/12

The created ini file seams to be ok: 

[setup]
servername = server
domainname = linumxuster.lan
adminpw = a
skipfw = True > that should be ok

**Comment by zefanja** [comment]
Just tested and confirmed. `skipfw = True` does not skip the firewall setup.

**Comment by HappyBasher** [comment]
Fixed in 7.0.0-47.

**Comment by zefanja** [comment]
In the most recent version, skipping firewall config does not work in unattended mode, because the value in the custom.ini is not checked in `linuxmuster-setup`.
