### ISSUE TITLE
integrate devices manpage from sophomorix

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#21]
Please merge this manpage into yours:

https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/man/de/devices.csv.de.5

**Comment by HappyBasher** [comment]
Done. But shouldn't the man page be in english?

**Comment by jeffbeck** [comment]
I remodved 
https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/man/de/devices.csv.de.5 
from sophomorix4
