### ISSUE TITLE
linuxmuster-setup veraendert die Kartenzuordnung auf der opnsense

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-base7#23]
Hallo,

ich hab die aktuellen Appliances nun nochmal frisch aufgespielt.

Beim linuxmuster-setup auf dem Server werden die Lankartenzuweisungen auf der opnsense verändert.
Sie wird während des setups neu gestartet: danach kann keien Verbindung mehr zu ihr hergestellt werden, weil die Grüne LAN Karte nicht mehr korrekt zugewiesen ist.

Getestet mit Virtualbox.
Zuordnung der Karten war:
LAN em0
OPT1 em1
WAN em2

Viele Grüße

Holger

**Comment by HappyBasher** [comment]
Bitte konkreter. Was heißt genau "nicht mehr korrekt zugewiesen"? Wie sieht die Zuordnung nach dem setup aus?

**Comment by HappyBasher** [comment]
Fixed in 7.0.8.

**Comment by baumhof** [comment]
Ich habe es getestet: Problem tritt nach Update nicht mehr auf.
Ichhabe linuxmuster-setup auf dem Server der Testumgebung aufgerufen, dann alle Maschinen neu gestartet: LAN Kartenzuordnung auf OPNsense ist noch da.
Danke :-)
