### ISSUE TITLE
hostname changes after reboot

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#25]
I'm not sure if this a linuxmuster-base issue, but after running setup the hostname is set correctly.
After a reboot it is set back to `server`.

**Comment by zefanja** [comment]
Just check the `devices.csv`. It has this entry:

`server;firewall;nopxe;08:00:27:B5:D0:0C;10.0.0.254;;;;server;;0`

**Comment by HappyBasher** [comment]
It's a linuxmuster-prepare issue.
