### ISSUE TITLE
create devices.csv on setup with 15 fields

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#26]
The devices.csv created on setup should have all 15 fields and should look like:

server;firewall;nopxe;02:4F:56:23:00:BB;10.0.0.254;;;;server;;0;;;;SETUP;

the SETUP in the comment (field 15) tells the migration script to keep this line while migration adds the (modified) content of the workstation file of linuxmuster 6.x

**Comment by HappyBasher** [comment]
I think the migration script should always keep the existing devices on the target server despite of the entries in devices.csv. Any other behaviour does not make sense.

**Comment by jeffbeck** [comment]
The problem is, that the migration script can be run twice or more (until devices.csv is perfect).
If it always keeps the existing data, the migration data is accumulating.


So the must be something 

could also add a 'special line' in devices.csv:

`######### Migration data follows - keep this line until migration is finished ############`

Then the migration script reads  until this line, and recreates the rest.

**Comment by jeffbeck** [comment]
ON migration the following happens to devices.csv

1) Read devices.csv (from setup or previous migration run) until:
    A) End of file (from setup)
    B) special line (appended from previous migration run)
2) Append Migration data

So the line from the first post is not necessary anymore.

It still is a good idea to use the comment field (15) to show what device entries were done on setup.

**Comment by HappyBasher** [comment]
Fixed in 7.0.9.
