### ISSUE TITLE
call: sophomorix-device --sync

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#27]
with sophmorix 3.51.3-1 you can call sophomorix-device as:

`sophomorix-device --dry-run`

for syntax test only (returns errors count, 0 is syntax error free) 

and

`sophomorix-device --sync`

for synchronisation.

The old call:

`sophomorix-device`

still works for now.

Please give me a note, when a linuxmuster-base7 package with the new calls is uploaded.
Then I will show the help as a result of the old call.

**Comment by HappyBasher** [comment]
Fixed in 7.0.9.

**Comment by jeffbeck** [comment]
Changed also in sophomorix

**Comment by jeffbeck** [comment]
I reopen this issue to verify:

Does `linuxmuster-import-devices` do the following with `sophomorix-device`:

1) `sophomorix-device --dry-run`
     Exit if return value is NOT 0
2) Go on and do linuxmuster stuff and synchronize AD with:
    `sophomorix-device --sync`

Does this work this way now??

**Comment by jeffbeck** [comment]
Please confirm if this is handled correctly

**Comment by HappyBasher** [comment]
Done!
