### ISSUE TITLE
samba expect server.* vert and key files, but files are named servername.*

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#28]
When the server name is not server, linuxmuster-setup creates servername.cert and *.key files. This causes problems with samba because it fails to start the LDAP server. See [#29](https://github.com/linuxmuster/sophomorix4/issues/29) here.

**Comment by HappyBasher** [comment]
Fixed in 7.0.6.

**Comment by zefanja** [comment]
Thanks for the fast fix! That's great!
