### ISSUE TITLE
adding global-admin on setup failes sometimes

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#31]
the creation of global-admin still fails sometimes (tested 4.8.18)
#### No connection to Samba4 AD!                                          ####

while the creation of the global bind user works (done after adding global-admin)

Please add a wait statement (3 seconds should be enough) or check if samba ist running, before adding the global admin

see also #32

**Comment by HappyBasher** [comment]
Should be fixed.
