### ISSUE TITLE
testing return value of sophomorix-admin on setup

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#32]
When sophomorix-admin fails, the setup command shows:
#### Creating samba account for global-admin ................... Success! ####

but sophomorix -admin has failed loke so:

#### No connection to Samba4 AD!                                          ####
Calling console printout
ERROR   -1: No connection to Samba4 AD!    

Please check the return value of sophomorix-admin: 0 success, all other: failed

**Comment by HappyBasher** [comment]
Can be closed I think.
