### ISSUE TITLE
Devices looks like to be updated, although nothing changed

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#36]
When I add a new device and re-run `linuxmuster-import-devices` again and again, it looks like that all the entries in devices.csv get updated every time. Is this the expected behavior?

![peek 2018-10-10 19-57](https://user-images.githubusercontent.com/708888/46737970-181e5780-ccc7-11e8-8b50-9792d0273daf.gif)

**Comment by HappyBasher** [comment]
The checks are done by sophomorix-device which is invoked by linuxmuster-import-devices. So this is more like a sophomorix related issue.

**Comment by HappyBasher** [comment]
Can be closed I think.
