### ISSUE TITLE
Feature Request: Add option in start.conf to configure GRUB (timeout, default)

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#38]
Cross-Reference to https://github.com/linuxmuster/linuxmuster-linbo/issues/96
(because import_workstations also changes/creates grub.cfg and I don't know where it belongs to)

**Comment by HappyBasher** [comment]
Because the modification of timeout and default boot in the grub.cfg has an immediate effect on the next boot there is no need to write it first to the start.conf and then invoke the import script. Furthermore, the information is not required at any other point.

**Comment by zefanja** [comment]
The idea was to have these fields in the start.conf to configure GRUB without manual editing the group.cfg file. 

Use case: On linux-only systems many don't boot to linbo but directly boot to the OS.

**Comment by HappyBasher** [comment]
What is better?

1. Modify start.conf, invoke import script and wait several minutes.
2. Modify grub.cfg and start over immediately.

**Comment by zefanja** [comment]
Second option - sure, but from a user point of view it would be better, if you can change all things in one location. All settings are done in start.conf. It would be more consistent.
