### ISSUE TITLE
Set language for firewall on setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#40]
https://github.com/linuxmuster/linuxmuster-base7/blob/4d19596bdb06e28f7909ca032be0bb2fbf243a6c/share/firewall/opnsense/config.xml.tpl#L243

The language shouldn't be hard-coded. Better would be to use the system language or don't change it at all (leave it, like the user set it up).

**Comment by HappyBasher** [comment]
Fixed in 7.0.22.
