### ISSUE TITLE
IP Adress in wiki doc wrong

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-base7#42]

**Comment by jolly-jump** [comment]
Hi, 

your screenshot in the doc: https://github.com/linuxmuster/linuxmuster-base7/wiki/Ersteinrichtung-der-Appliances
shows the wrong IP: 10.16.1.1, while it should be 10.16.1.254 as in the text.
See right picture attached.

Can't make a pull-request on the wiki docs, sorry.


![opnsense-lan-interface](https://user-images.githubusercontent.com/2824334/48680436-dfae4b00-eb9b-11e8-81aa-2eeea7efb6d4.png)

**Comment by HappyBasher** [comment]
Thanks. Fixed now.
