### ISSUE TITLE
New VMs 09112018: Inconsistent ethernet device naming

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-base7#45]
The docker VM uses enp3s0 whereas serve vm uses eth0 ethernet device naming. At the beginning this is a bit confusing, as ubuntu 18.04 also introduces the new network management tool netplan.

**Comment by HappyBasher** [comment]
Fixed in current ovas. Interface name is always eth0 from now on (excluding opnsense).
