### ISSUE TITLE
add a comment to admins added by setup

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#50]
On setup 2 admins are created:
+----------------------+-+-------------------------+------+--------------------------------+
| Administrator        |P| displayName             | Role | Comment                        |
+----------------------+-+-------------------------+------+--------------------------------+
| global-admin         |F| Global Admin            | gadm | created by sophomorix          |
| global-binduser      |T| Global Binduser         | gbin | created by sophomorix          |
+----------------------+-+-------------------------+------+--------------------------------+

The comment is the default comment "created by sophomorix"

It would be nicer if a describing comment is used like  'created by linuxmuster-base7 on initial setup'

**Comment by HappyBasher** [comment]
Fixed in 7.0.29.
