### ISSUE TITLE
obsolete logon scripts

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#51]
The following files seem to be created by linuxmuster-setup and are obsolete:

1)
/var/lib/samba/sysvol/linuxmuster.local/scripts/linux/login.script
-> modified by linuxmuster-setup at 20181127080419

and

2) 
/var/lib/samba/sysvol/linuxmuster.local/scripts/windows/login.cmd
-> # modified by linuxmuster-setup at 20181127080419

The new scripts under 
/var/lib/samba/sysvol/linuxmuster.local/scripts/<school>
are managed by sophomorix

**Comment by HappyBasher** [comment]
Fixed in 7.0.22.
