### ISSUE TITLE
Linuxmuster Setup overrides IP Settings

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-base7#59]
When using a different IP settings  than provided by default the linuxmuster setup changes this back.

Is this by design and using a different IP settings have to be set after the setup instead of before?

**Comment by PLanB2008** [comment]
My fault - changing ip adress has to be done usign lmn7-appliance script instead of just changing the ip address...

**Comment by PLanB2008** [comment]
Okay, problem was ./lmn-appliance needs internet connection as well, without it aborts and the the configuration is not written.

**Comment by HappyBasher** [comment]
I use a similar setup with static wan settings on the firewall. In my past setup attempts the network settings remained untouched and there was no internet connection problem. I'll check this as soon as there is a functional linuxmuster-webui7 package.

**Comment by PLanB2008** [comment]
I think the issue is not about the firewall, its about running prepare script without having an internet connection. 
I was playing around trying to get it working and did some things which didn't help but added some to the confusion.

First I did lmn7-appliance without specified the network. Then I moved the appliance to a place without internet and figured out the network does not fit.
So i ran lmn7-appliance again, and this could not finish without internet access.

**Comment by HappyBasher** [comment]
lmn7-appliance only works with internet connection because it's purpose is the download of the necessary packages for linuxmuster-setup. Use linuxmuster-prepare instead.

**Comment by HappyBasher** [comment]
So at least this issue is not about "Linuxmuster Setup overrides IP Settings" at all?

**Comment by PLanB2008** [comment]
I didn't know theres a difference between lmn7-appliance and linuxmuster-prepare.

Sorry I keep mixing up these script... If linuxmuster-prepare works for chaning IP adress we can close the issue, yes.

**Comment by HappyBasher** [comment]
Done.
