### ISSUE TITLE
no way to cancel setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#60]
There is no way to cancel the setup. I would be helpful to have such an option. `Ctrl+C` just cancels the current command / module.

**Comment by PLanB2008** [comment]
We could possibly add this. Theres just one porblem: If something goes wrond during the inital setup we are not sure if the installation ran fine. There is no option to run the prepare process a second time. Right now, if the preparing process fails you should start over.

**Comment by HappyBasher** [comment]
In fact hitting `Ctrl+C` one time only the current submodule is cancelled. You have to hit `Ctrl+C` mutiple times to cancel the overall process. After that you may start `linuxmuster-setup` again with corrected parameters and bring the setup to a successful end.
I think this can be closed.
