### ISSUE TITLE
star.conf serverip gets overwritten

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-base7#63]
When I change the serverip in my start.conf.IMAGENAME it gets overwritten on every linuxmuster-import-devices.

**Comment by HappyBasher** [comment]
It's been that way since the beginning of time. What is wrong with it? The server ip is the server ip. If you want to use a different linbo server address modify the kerneloptions in start.conf accordingly (see example files).

**Comment by PLanB2008** [comment]
This would not work in a multischool environment where the client server is doing linbo authentication because the server is always referenced via this IP.
Is there any benefit I miss overwriting this values? As far as I see we do not overwrite any other value?

**Comment by HappyBasher** [comment]
So this will be fixed when linbo gets multischool capable.

**Comment by HappyBasher** [comment]
Fixed with #117?

**Comment by PLanB2008** [comment]
Closed for now
