### ISSUE TITLE
Computer is not a valid role in sophomorix anymore

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-base7#64]
Hello @HappyBasher 

https://github.com/linuxmuster/linuxmuster-base7/blob/a02465d1614be0bad50f53b4bc081bc09ba9115b/share/templates/devices.csv#L7

Computer is not a valid role in sophomorix anymore and maybe this example should be updated.
It can confuses the user ( see : https://ask.linuxmuster.net/t/geraet-in-der-schulkonsole-hinzufuegen-geloest/3302 ).

**Comment by HappyBasher** [comment]
Fixed in linuxmuster-base7 7.0.35.
