### ISSUE TITLE
smb.conf:  name resolve order

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-base7#65]
FQDN   \\server.linuxmuster.lan... does not work, when the server has no internet access.

this migght be fixed with a correct parameter/order in smb.conf:

name resolve order =

**Comment by HappyBasher** [comment]
This issue has IMO nothing to do with name resolve order. Testing all combinations of lmhosts wins host bcast did not fix.

**Comment by HappyBasher** [comment]
Note that 7.0.38 does not fix the obscure behaviour of smbclient timeout without dns forwarder. This is a workaround so that the setup goes through. The definition of the dns forwarder is only carried out after the samba ad setup.
