### ISSUE TITLE
default-school share params

### ISSUE THREAD

**Issue by netzint** [linuxmuster/linuxmuster-base7#68]
The default params for "default-school" share are incorect. The "linuxmuster-global" sections is ok. 

[default-school]
        path = /srv/samba/schools/default-school
        guest ok = no
        read only = no

[linuxmuster-global]
        path = /srv/samba/global
        comment = Share for school global
        guest ok = no
        read only = no
        msdfs root = no
        hide unreadable = yes
        valid users = LINUXMUSTER\administrator, @LINUXMUSTER\SCHOOLS
        strict allocate = yes

**Comment by HappyBasher** [comment]
The default-school share is created in consultation with Rüdiger this way:
`net conf addshare default-school  /srv/samba/schools/default-school writeable=y guest_ok=n`
What is wrong with it?

**Comment by HappyBasher** [comment]
`[linuxmuster-global]` is created by sophomorix, `[default-school]` by linuxmuster-setup. However `net conf addshare` does not allow more options. If `[default-school]` has to be configured identical to `[linuxmuster-global]` then I have to place the share defintion directly into smb.conf. But that was not desired at the time. So what to do now?

**Comment by netzint** [comment]
You can add params with:

net conf setparm default-school „hide unreadable“ yes

- send from mobile -

**Comment by netzint** [comment]
Freigabe im Samba Format auflisten:
`net conf list`

Ein Parameter einer Freigabe hinzufügen:
`net conf setparm default-school „hide unreadable“ yes`

Ein Parameter einer Freigabe löschen:
`net conf delparm default-school „hide unreadable“`
