### ISSUE TITLE
Inklusionsdatei um ini-Dateien zu lesen und zu schreiben

### ISSUE THREAD

**Issue by ironiemix** [linuxmuster/linuxmuster-base7#7]
Es wäre schön, wenn alle linuxmuster Shell Skripte dieselbe Methode zum lesen/schreiben von ini-datein verwenden würden.

https://github.com/albfan/bash-ini-parser
https://github.com/rudimeier/bash_ini_parser

**Comment by HappyBasher** [comment]
Shell scripts can read the linuxmuster system environment variables and setup.ini with  
`source /usr/share/linuxmuster/defaults.sh`  
There is no further need for shell scripts to read/write any ini files.
