### ISSUE TITLE
After command line setup login to secure WebUI only after server restart

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-base7#72]
I did a new install of linuxmuster server (dist-upgrade from July 23rd). When installation is finished, login using https is not possible. Only after restarting of server, login is possible. In the WebUI-setup the login works directly after the setup script is finished.

**Comment by HappyBasher** [comment]
In fact this is an WebUI issue. AFAIK this is fixed in the meantime.
