### ISSUE TITLE
No option to set language on command line setup

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-base7#73]
Using linuxmuster-setup the setup requests several installation information. Unfortunately, no question for the language of the system is shown, hence the system language is English (I don't know, how to change the language afterwards, the WebUI does not have that possibility).

**Comment by zefanja** [comment]
You can change the system language with `sudo dpkg-reconfigure locales` (https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/)

**Comment by HappyBasher** [comment]
linuxmuster.net 7 uses the system language. Therefore change the system language as mentioned above.
