### ISSUE TITLE
/etc/samba/smb.conf missing option

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-base7#78]
Samba configuration should contain this option by default:

    time server = yes

This is used for windows machines for time synchronization.

(see https://wiki.samba.org/index.php/Time_Synchronisation)

In addition the ntp servicec server should be enabled by default.

    systemctl enable ntp

**Comment by HappyBasher** [comment]
Additionally the time server address in dhcpd.conf has to be changed to the server ip.

**Comment by HappyBasher** [comment]
Time server services are enabled in linuxmuster-base7 7.0.45.
