### ISSUE TITLE
make a backup of the firewall configuration before pushing a new one

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#8]
Currently the old/original firewall configuration is deleted after running `m_firewall.py`. From a user point of view there should be backup to revert changes if needed.

**Comment by HappyBasher** [comment]
Use the capabilities of your hypervisor and make a snapshot before you run setup.

**Comment by zefanja** [comment]
But the current version of `m_firewall.py` actually downloads the current config? Why not just save it as a backup? 

Some people run their firewall on bare-metal. Sure they can make a backup, but the it has to be documented. 

v6.2 has this feature - why not in v7?

**Comment by HappyBasher** [comment]
OPNsense creates a config backup on every boot in /conf/backup.

**Comment by zefanja** [comment]
> OPNsense creates a config backup on every boot in /conf/backup.

Sounds good!
