### ISSUE TITLE
school.conf SCHOOL_LONGNAME empty

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-base7#82]
> During Setup a name for the school was entered. However, when opening administrative webui at school data the name "Default School" is shown and must be changed then.

During setup we get the Name of the school, this is used for ssl etc.
This schoolname should fille

SCHOOL_LONGNAME
by default during the setup.

https://github.com/linuxmuster/linuxmuster-webui7/issues/87

**Comment by HappyBasher** [comment]
The implemented solution does not work since school.conf cannot be treated as an ini file. Not fixed yet.

**Comment by HappyBasher** [comment]
Depends on https://github.com/linuxmuster/sophomorix4/issues/103.
