### ISSUE TITLE
opnsense web-proxy sso: time until ad group changes take effect

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-base7#83]
The time it takes for active directory group changes to take effect is too long, making the internet blocking of users impractical.

**Comment by HappyBasher** [comment]
Fixed in 7.0.49:
- https://github.com/linuxmuster/linuxmuster-base7/commit/2e4926ff47554a76a11fcc5ac5abec501e900b19
- https://github.com/linuxmuster/linuxmuster-base7/commit/7694a21d861088bfe621d01e45f219325ebd8c08
- https://github.com/linuxmuster/linuxmuster-base7/commit/5809d2b030cdfb103cdaa7c0a8b7d8142815f393

Providing configfile `/usr/local/etc/squid/auth/credentialsttl.conf` which contents
```auth_param basic credentialsttl 1 minute```  
and ensures that a change of the internet group of a user takes effect after one minute.

**Comment by kiarn** [comment]
Great ! Thanks !

**Comment by roesslerrr** [comment]
Ich habe versucht Version 7.0.49 zu installieren, das scheitert aber an der ssh-Verbindung zur opnsense:
<snip>
linuxmuster-base7 (7.0.49-0ubuntu0) wird eingerichtet ...
Listing '/usr/lib/linuxmuster'...
Compiling '/usr/lib/linuxmuster/constants.py'...
Compiling '/usr/lib/linuxmuster/functions.py'...
Listing '/usr/lib/linuxmuster/setup.d'...
Compiling '/usr/lib/linuxmuster/setup.d/a_ini.py'...
Compiling '/usr/lib/linuxmuster/setup.d/c_general-dialog.py'...
Compiling '/usr/lib/linuxmuster/setup.d/d_templates.py'...
Compiling '/usr/lib/linuxmuster/setup.d/e_fstab.py'...
Compiling '/usr/lib/linuxmuster/setup.d/g_ssl.py'...
Compiling '/usr/lib/linuxmuster/setup.d/h_ssh.py'...
Compiling '/usr/lib/linuxmuster/setup.d/i_samba-provisioning.py'...
Compiling '/usr/lib/linuxmuster/setup.d/j_samba-users.py'...
Compiling '/usr/lib/linuxmuster/setup.d/k_add-server.py'...
Compiling '/usr/lib/linuxmuster/setup.d/m_firewall.py'...
Compiling '/usr/lib/linuxmuster/setup.d/n_linbo.py'...
Compiling '/usr/lib/linuxmuster/setup.d/o_opsi.py'...
Compiling '/usr/lib/linuxmuster/setup.d/p_mail.py'...
Compiling '/usr/lib/linuxmuster/setup.d/w_webui.py'...
Compiling '/usr/lib/linuxmuster/setup.d/z_final.py'...


Decreasing credentialsttl value in opnsense's web-proxy sso configuration.

ssh: connect to host 10.160.1.254 port 22: Connection timed out
lost connection
dpkg: Fehler beim Bearbeiten des Paketes linuxmuster-base7 (--configure):
 installed linuxmuster-base7 package post-installation script subprocess returned error exit status 1
<snap>

Wie wird normalerweise die ssh-Verbindung aufgebaut? Spezieller Port?
nmap zeigt mir keinen Hinweis.
Not shown: 996 filtered ports
PORT     STATE SERVICE
53/tcp   open  domain
80/tcp   open  http
443/tcp  open  https
3128/tcp open  squid-http

Gruß - Rainer

**Comment by roesslerrr** [comment]
Für ssh auf opnsense ist es Port 10022.
Das Script scheint aber auf Port 22 zu versuchen ...

**Comment by HappyBasher** [comment]
> Für ssh auf opnsense ist es Port 10022.
> Das Script scheint aber auf Port 22 zu versuchen ...

Das kann es eigentlich nicht geben. Auf der OPNsense, die wir ausliefern und die während des Setups per SSH konfiguriert wird, läuft der SSH-Dienst auf dem Standardport. Kaum zu glauben, dass eure Firewall richtig konfiguriert ist.

**Comment by roesslerrr** [comment]
Tatsächlich hab ich die opnsense großteils von Hand konfiguriert.
Wenn ich mich recht erinnere ist mir die opnsense immer um die Ohren geflogen, als ich das subnetting konfiguriert habe.
Ist aber schon lange her.

Dann pack ich den Eintrag "auth_param basic credentialsttl 1 minute" von Hand nach  /usr/local/etc/squid/auth/credentialsttl.conf 
und starte dann den squid neu?!

**Comment by HappyBasher** [comment]
Das kannst du so machen. Allerdings weiß ich nicht, ob das auf dieser OPNsense wie gewünscht funktionieren wird.

**Comment by roesslerrr** [comment]
Ich hab den opnsense-ssh-Dienst jetzt auf Port 22 gestellt. Damit läuft das post-install-Script durch. So weit, so gut. 
Da es nicht viel an Änderung ist, bin ich sehr zuversichtlich, dass es keine Probleme gibt. Morgen im Regelbetrieb bin ich schlauer.

Warum der Port allerdings auf 10022 stand, ist mir unerklärlich. Ich kann mich nicht erinnern daran geschraubt zu haben und meine Doku weiß auch nichts davon. 

Bei der Grundinstallation (Sommer 2019) bin ich nach Anleitung vorgegangen. Erst beim Einrichten des Subnetting musste ich abweichen, da das Subnetting-Script die opnsense reproduzierbar zerstört hat. Da wir einen ungewöhnlichen IP-Adressraum haben (10.160...), habe ich es darauf geschoben und die Subnetting-Einstellungen auf opnsense von Hand eingetragen.

**Comment by HappyBasher** [comment]
Unfortunately the problem persists so further research has to be done.

**Comment by HappyBasher** [comment]
A supplemental squid config file _[/usr/local/etc/squid/pre-auth/50-linuxmuster.auth.conf](https://github.com/linuxmuster/linuxmuster-base7/blob/master/share/firewall/opnsense/50-linuxmuster.auth.conf)_ adds an external acl, which queries active directory whether the user is member of the internet group. After 60 seconds a group change will be effective.
