### ISSUE TITLE
NoProxy Aliases in OPNsense after setup

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-base7#84]
It would be nice if the setup would delete the not used NoProxy Alias Entries at the end of Setup.
A Networkuser knowing that the IPs from x.y.z.1 to x.y.z.10 are in the noProxy Alias file might use it to give his own device such an IP.
At the end of setup the setuproutine knows which additional Servers are in use (docker, OPSI) and might be able to delete the unused IPs.

Yours
Holger

**Comment by HappyBasher** [comment]
How should the setup know which ips are not used by the administrator? The mentioned range is reserved for administration in common, not only for additional appliances.
