### ISSUE TITLE
Context user

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-base7#86]
Hello @HappyBasher !

We need some system users in order to restrict the sophomorix command : 

a) student
b) teacher
c) bsz-student
d) bsz-teacher

Without home, without login, with bash, and sudoers file in sudoers.d with e.g. : 

    bsz-student ALL=(ALL) NOPASSWD: /usr/sbin/sophomorix-query
    bsz-student ALL=(ALL) NOPASSWD: /usr/sbin/sophomorix-passwd

(same for student) 

Thanks !

Arnaud

**Comment by HappyBasher** [comment]
Which group, which uid?

**Comment by HappyBasher** [comment]
Proposal:

- group: nogroup (65534)
- teacher: uid 1001
- student: uid 1002
- shell: /bin/sh
- home: /home/$USER

OK?

**Comment by kiarn** [comment]
Is /home/$USER necessary ?
uid 1001 may be already used, but it's not important, because I will get the uid with the username.

**Comment by HappyBasher** [comment]
Ok, it works without home dir and we use uids 901 and 902.
