### ISSUE TITLE
MAC-Check

### ISSUE THREAD

**Issue by ni-kw** [linuxmuster/linuxmuster-base7#93]
![grafik](https://user-images.githubusercontent.com/16056721/79231732-cf6ccf00-7e66-11ea-8176-3ba24f3815d3.png)
WebUI saves the MAC-Address like this
Import ends without an error.

Also the restarting servces Output shows "OK!" for the dhcp server
![grafik](https://user-images.githubusercontent.com/16056721/79231968-2bcfee80-7e67-11ea-96bc-5ae6543d8e41.png)

But DHCP-Service is not running and can't start:
![grafik](https://user-images.githubusercontent.com/16056721/79231944-207cc300-7e67-11ea-907b-b2776e41bf95.png)

![grafik](https://user-images.githubusercontent.com/16056721/79231953-25417700-7e67-11ea-823d-58d4f607e18d.png)

**Comment by kiarn** [comment]
Hello @ni-kw,

I cannot reproduce this : I mean in the last versions of the webui the mac adresses are tested to follow the MAC notation with ":" only, and not with '-'.

Even if I try to write it directly in the file `devices.csv`, the webui shows an error by the save action.

Do you have the latest version of the webui ?
Maybe a problem with the browser ?

**Comment by ni-kw** [comment]
Webui is not the latest release. I didn't think that is allready fixed ^^
Even the webui shows an error - can you start the import with linuxmuster-import-devices? I think the import-script have to filter the "-" too

I can not update that server to test the latest version of lmn-base at the moment - but can test it this evening.

**Comment by HappyBasher** [comment]
The complete value checking is done by sophomorix-device. So open an issue there, if mac addresses should be checked.

**Comment by ni-kw** [comment]
Ok, thanks. I let this issue open, the only thing left is that the import-scripts output is `isc-dhcp-server.....OK!` but it didn't really starts.

**Comment by jeffbeck** [comment]
Please do a sophomorix syntax check with:

`  sophomorix-device --dry-run  (returns a json object with syntax check results)`

Are there complaints about the MAC?

**Comment by ni-kw** [comment]
Yes:
`root@server:~# sophomorix-device --dry-run
Command line::
Option verbose is a modifier option
Option json is a modifier option
Hmmh. do not know what to do with option info
* forcing info mode
Option combinations successfully checked
OK: SophomorixSchemaVersion 1 matches required Version 1
#### Reading /usr/share/sophomorix/devel/sophomorix.ini                   ####
Distro-check: Ubuntu 18.04 is OK
#### Reading /etc/samba/smb.conf                                          ####
#### Reading /usr/lib/linuxmuster-webui/etc/default-ui-permissions.ini    ####
#### Parsing: net conf list                                               ####
#### Asking domain passwordsettings from samba                            ####
#### Reading /usr/share/sophomorix/devel/master/sophomorix.conf.master    ####
#### Reading /etc/linuxmuster/sophomorix/sophomorix.conf                  ####
#### OK: default-school share exists                                      ####
#### OK: /etc/linuxmuster/sophomorix/default-school/school.conf           ####
#### Reading /usr/share/sophomorix/devel/master/school.conf.master        ####
#### Reading /etc/linuxmuster/sophomorix/default-school/school.conf       ####
#### Query AD for device (start)                                          ####
#### 216 Computers found in AD                                            ####
#### 28 sophomorix rooms/devicegroupes found in AD                        ####
#### 15 dnsZones found                                                    ####
#### 532 sophomorix dnsNodes found                                        ####
#### Sorting lists ...                                                    ####
#### Query AD for device (end)                                            ####
#### Reading /etc/linuxmuster/sophomorix/default-school/devices.csv       ####
invalid MAC address format: 3c-2c-30-3f-ab:19 at /usr/sbin/sophomorix-device line 1813.
`

I'm going to update the server to the latest verion and try it again. At the moment it's:
linuxmuster-base7                     7.0.45-0ubuntu0

**Comment by jeffbeck** [comment]
OK, also bricht sophomorix wegen der Fehlerhaften MAC ab

@ni-kw :

Please run 
sophomorix-device --dry-run
again and tell us the return value:

echo $?

This should NOT be zero (0)

**Comment by ni-kw** [comment]
`25`

**Comment by jeffbeck** [comment]
OK, thats what I tested to:

@HappyBasher : 
please fix this:
ONLY continuing if the resturn value of sophomorix-device --dry-run is 0

**Comment by jeffbeck** [comment]
I use a perl module to test for a correct mac address.
And the "-" delimiter is considered wrong syntax.

Is there any reason to allow "-" as a delimiter?

**Comment by ni-kw** [comment]
After Upgrade to latest version I can confirm:

- WebUI blocks the "-"
- sophomorix-device --dry-run >
`invalid MAC address format:`
- linuxmuster-import-devices >
```
#### Reading /etc/linuxmuster/sophomorix/default-school/devices.csv       ####
invalid MAC address format: 3c-2c-30-3f-ab:19 at /usr/sbin/sophomorix-device line 1813.
#### sophomorix-device finished  errors detected!                         ####
```
- If I manually set up a host in `/etc/dhcp/custom.conf` with "-" an then run linuxmuster-import-devices I get:
```
#### Restarting services:                                                 ####
#### * isc-dhcp-server .............................................. OK! ####
```
but the service isc-dhcp-server ist not running, it has failed at the (re)start.

So the only thing left to fix is the ".....OK!" But I think it's a long way you have to go to run into this issue. You can fix it if you like to, but (to me) it is not that important.

**Comment by HappyBasher** [comment]
The problem is that the return code of _systemctl start isc-dhcp-server_ is always **0** whether or not the action was successful.

**Comment by HappyBasher** [comment]
MAC-Check is not an issue. False feedback after service restart is fixed.
