### ISSUE TITLE
Repo does not work with Ubuntu 20.04: Repository not signed

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-base7#96]
I know, v7 only supported for 18.04, but since 20.04 was released last month I give it try, but it looks like apt does not accept the repository. Here is the error message (running the prepare script):

![grafik](https://user-images.githubusercontent.com/708888/81570406-c0782e80-93ca-11ea-89ba-1fcd97932422.png)

**Comment by HappyBasher** [comment]
This is no issue concerning to linuxmuster-base7.

**Comment by Letsric** [comment]
Hi,
I really like your solution, but I really think that v7 should be updated to Ubuntu 20.04,
or, 22.04, when it releases this April. Ubuntu server 18.04 has pretty old repos by now
and, as far as I know, **isn't even supported anymore by 2023**!
Overall, I would really appreciate it, if LM7 gets updated to a more modern Distro.
Thanks,
Eric

**Comment by Letsric** [comment]
OK ,
Thank you!
